
# coding: utf-8


"""fresh start

Revision ID: b91bade09607
Revises: 
Create Date: 2026-02-17 17:03:24.508692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b91bade09607'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_ip', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('classification', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_index(op.f('ix_alerts_severity'), 'alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_alerts_source_ip'), 'alerts', ['source_ip'], unique=False)
    op.create_table('incident',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_ip', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_source_ip'), 'incident', ['source_ip'], unique=False)
    op.create_table('incident_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('incident_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_events_id'), 'incident_events', ['id'], unique=False)
    op.create_table('ip_analysis',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ip', sa.String(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('risk', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('isp', sa.String(), nullable=True),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('asn', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('vt_malicious', sa.Integer(), nullable=True),
    sa.Column('vt_suspicious', sa.Integer(), nullable=True),
    sa.Column('vt_reputation', sa.Integer(), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ip_analysis_id'), 'ip_analysis', ['id'], unique=False)
    op.create_index(op.f('ix_ip_analysis_ip'), 'ip_analysis', ['ip'], unique=False)
    op.create_table('user_activity',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('target', sa.String(), nullable=True),
    sa.Column('page', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_activity_user'), 'user_activity', ['user'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_activity_user'), table_name='user_activity')
    op.drop_table('user_activity')
    op.drop_index(op.f('ix_ip_analysis_ip'), table_name='ip_analysis')
    op.drop_index(op.f('ix_ip_analysis_id'), table_name='ip_analysis')
    op.drop_table('ip_analysis')
    op.drop_index(op.f('ix_incident_events_id'), table_name='incident_events')
    op.drop_table('incident_events')
    op.drop_index(op.f('ix_incident_source_ip'), table_name='incident')
    op.drop_table('incident')
    op.drop_index(op.f('ix_alerts_source_ip'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_severity'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
